import { pgTable, uuid, text, timestamp } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { accounts } from "./accounts";

/**
 * projects — one workspace per product.
 * All tenant-scoped tables reference this via project_id.
 */
export const projects = pgTable("projects", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  accountId: uuid("account_id")
    .notNull()
    .references(() => accounts.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  description: text("description").notNull(),
  icpDescription: text("icp_description").notNull(),
  problemStatement: text("problem_statement").notNull(),
  /** Array of competitor names, e.g. ['Acme', 'Globex'] */
  competitorNames: text("competitor_names")
    .array()
    .notNull()
    .default(sql`'{}'`),
  /** Scraping keywords generated by the keyword-generation worker */
  keywords: text("keywords")
    .array()
    .notNull()
    .default(sql`'{}'`),
  /** Subreddit candidates generated by the keyword-generation worker */
  subredditCandidates: text("subreddit_candidates")
    .array()
    .notNull()
    .default(sql`'{}'`),
  /** active | archived | deleted */
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

export type Project = typeof projects.$inferSelect;
export type NewProject = typeof projects.$inferInsert;
